import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import AllProviders from "@/components/Providers/AllProviders";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="id" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased m-3 bg-white text-black dark:bg-slate-950 dark:text-white`}
      >
        <AllProviders>
          {children}
        </AllProviders>
      </body>
    </html>
  );
}
